DROP TABLE IF EXISTS fin;


CREATE TABLE fin(
        high_NVDA TEXT NOT NULL,
        high_SOXX TEXT NOT NULL,
        low_SOXX TEXT NOT NULL,
        open_SOXX TEXT NOT NULL,
        close_SOXX TEXT NOT NULL,
        volume_SOXX TEXT NOT NULL,
        adjclose_SOXX TEXT NOT NULL,
        high_BTC TEXT NOT NULL,
        low_BTC TEXT NOT NULL,
        open_BTC TEXT NOT NULL,
        close_BTC TEXT NOT NULL,
        volume_BTC TEXT NOT NULL,
        adjclose_BTC TEXT NOT NULL,
        high_NVDA TEXT NOT NULL,
        high_SOXX TEXT NOT NULL,
        low_SOXX TEXT NOT NULL,
        open_SOXX TEXT NOT NULL,
        close_SOXX TEXT NOT NULL,
        volume_SOXX TEXT NOT NULL,
        adjclose_SOXX TEXT NOT NULL,
        high_BTC TEXT NOT NULL,
        low_BTC TEXT NOT NULL,
        open_BTC TEXT NOT NULL,
        close_BTC TEXT NOT NULL,
        volume_BTC TEXT NOT NULL,
        adjclose_BTC TEXT NOT NULL,
        high_NVDA TEXT NOT NULL,
        high_SOXX TEXT NOT NULL,
        low_SOXX TEXT NOT NULL,
        open_SOXX TEXT NOT NULL,
        close_SOXX TEXT NOT NULL,
        volume_SOXX TEXT NOT NULL,
        adjclose_SOXX TEXT NOT NULL,
        high_BTC TEXT NOT NULL,
        low_BTC TEXT NOT NULL,
        open_BTC TEXT NOT NULL,
        close_BTC TEXT NOT NULL,
        volume_BTC TEXT NOT NULL,
        adjclose_BTC TEXT NOT NULL,
        high_NVDA TEXT NOT NULL,
        high_SOXX TEXT NOT NULL,
        low_SOXX TEXT NOT NULL,
        open_SOXX TEXT NOT NULL,
        close_SOXX TEXT NOT NULL,
        volume_SOXX TEXT NOT NULL,
        adjclose_SOXX TEXT NOT NULL,
        high_BTC TEXT NOT NULL,
        low_BTC TEXT NOT NULL,
        open_BTC TEXT NOT NULL,
        close_BTC TEXT NOT NULL,
        volume_BTC TEXT NOT NULL,
        adjclose_BTC TEXT NOT NULL,
        high_NVDA TEXT NOT NULL,
        high_SOXX TEXT NOT NULL,
        low_SOXX TEXT NOT NULL,
        open_SOXX TEXT NOT NULL,
        close_SOXX TEXT NOT NULL,
        volume_SOXX TEXT NOT NULL,
        adjclose_SOXX TEXT NOT NULL,
        high_BTC TEXT NOT NULL,
        low_BTC TEXT NOT NULL,
        open_BTC TEXT NOT NULL,
        close_BTC TEXT NOT NULL,
        volume_BTC TEXT NOT NULL,
        adjclose_BTC TEXT NOT NULL
);


