DROP TABLE IF EXISTS fin;


CREATE TABLE fin(
        Date TEXT NOT NULL,
        high_NVDA DECIMAL(5,5),
        high_SOXX DECIMAL(5,5),
        low_SOXX DECIMAL(5,5),
        open_SOXX DECIMAL(5,5),
        close_SOXX DECIMAL(5,5),
        volume_SOXX DECIMAL(5,5),
        adjclose_SOXX DECIMAL(5,5),
        high_BTC DECIMAL(5,5),
        low_BTC DECIMAL(5,5),
        open_BTC DECIMAL(5,5),
        close_BTC DECIMAL(5,5),
        volume_BTC DECIMAL(5,5),
        adjclose_BTC DECIMAL(5,5),
        high_NVDA1 DECIMAL(5,5),
        high_SOXX1 DECIMAL(5,5),
        low_SOXX1 DECIMAL(5,5),
        open_SOXX1 DECIMAL(5,5),
        close_SOXX1 DECIMAL(5,5),
        volume_SOXX1 DECIMAL(5,5),
        adjclose_SOXX1 DECIMAL(5,5),
        high_BTC1 DECIMAL(5,5),
        low_BTC1 DECIMAL(5,5),
        open_BTC1 DECIMAL(5,5),
        close_BTC1 DECIMAL(5,5),
        volume_BTC1 DECIMAL(5,5),
        adjclose_BTC1 DECIMAL(5,5),
        high_NVDA2 DECIMAL(5,5),
        high_SOXX2 DECIMAL(5,5),
        low_SOXX2 DECIMAL(5,5),
        open_SOXX2 DECIMAL(5,5),
        close_SOXX2 DECIMAL(5,5),
        volume_SOXX2 DECIMAL(5,5),
        adjclose_SOXX2 DECIMAL(5,5),
        high_BTC2 DECIMAL(5,5),
        low_BTC2 DECIMAL(5,5),
        open_BTC2 DECIMAL(5,5),
        close_BTC2 DECIMAL(5,5),
        volume_BTC2 DECIMAL(5,5),
        adjclose_BTC2 DECIMAL(5,5),
        high_NVDA3 DECIMAL(5,5),
        high_SOXX3 DECIMAL(5,5),
        low_SOXX3 DECIMAL(5,5),
        open_SOXX3 DECIMAL(5,5),
        close_SOXX3 DECIMAL(5,5),
        volume_SOXX3 DECIMAL(5,5),
        adjclose_SOXX3 DECIMAL(5,5),
        high_BTC3 DECIMAL(5,5),
        low_BTC3 DECIMAL(5,5),
        open_BTC3 DECIMAL(5,5),
        close_BTC3 DECIMAL(5,5),
        volume_BTC3 DECIMAL(5,5),
        adjclose_BTC3 DECIMAL(5,5),
        high_NVDA4 DECIMAL(5,5),
        high_SOXX4 DECIMAL(5,5),
        low_SOXX4 DECIMAL(5,5),
        open_SOXX4 DECIMAL(5,5),
        close_SOXX4 DECIMAL(5,5),
        volume_SOXX4 DECIMAL(5,5),
        adjclose_SOXX4 DECIMAL(5,5),
        high_BTC4 DECIMAL(5,5),
        low_BTC4 DECIMAL(5,5),
        open_BTC4 DECIMAL(5,5),
        close_BTC4 DECIMAL(5,5),
        volume_BTC4 DECIMAL(5,5),
        adjclose_BTC4 DECIMAL(5,5)
        
);


